# Generated by Django 3.1.4 on 2020-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local'),
        ),
    ]
