# Generated by Django 3.1.4 on 2020-12-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_local_evento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
